/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-05-20 20:19:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ShowPatientMedicalHistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Java%20Training/JspProg/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HospitalManagementSystem/WEB-INF/lib/jsf-impl-2.2.20.jar!/META-INF/html_basic.tld", Long.valueOf(1564540038000L));
    _jspx_dependants.put("jar:file:/C:/Java%20Training/JspProg/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HospitalManagementSystem/WEB-INF/lib/jsf-impl-2.2.20.jar!/META-INF/jsf_core.tld", Long.valueOf(1564540022000L));
    _jspx_dependants.put("/WEB-INF/lib/jsf-impl-2.2.20.jar", Long.valueOf(1747126011539L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fstyleClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fvar_005fvalue_005fstyleClass_005frendered;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcolumn;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fstyleClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fvar_005fvalue_005fstyleClass_005frendered = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcolumn = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
    _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass.release();
    _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fstyleClass_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fvar_005fvalue_005fstyleClass_005frendered.release();
    _005fjspx_005ftagPool_005fh_005fcolumn.release();
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:view
    com.sun.faces.taglib.jsf_core.ViewTag _jspx_th_f_005fview_005f0 = new com.sun.faces.taglib.jsf_core.ViewTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fview_005f0);
    try {
      _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fview_005f0.setParent(null);
      _jspx_th_f_005fview_005f0.setJspId("jsp_1705704282_0");
      int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fview_005f0);
        }
        do {
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("    <meta charset=\"UTF-8\">\r\n");
          out.write("    <title>Show Patient Medical History</title>\r\n");
          out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
          out.write("</head>\r\n");
          out.write("<body class=\"bg-gray-100 min-h-screen p-10\">\r\n");
          out.write("\r\n");
          out.write("    <div class=\"max-w-5xl mx-auto bg-white p-8 rounded shadow-md\">\r\n");
          out.write("        <h2 class=\"text-2xl font-semibold text-blue-800 mb-6\">📋 Medical History by Patient ID</h2>\r\n");
          out.write("\r\n");
          out.write("        ");
          if (_jspx_meth_h_005fform_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    </div>\r\n");
          out.write("\r\n");
          out.write("</body>\r\n");
          out.write("</html>\r\n");
          int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fview_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    com.sun.faces.taglib.html_basic.FormTag _jspx_th_h_005fform_005f0 = new com.sun.faces.taglib.html_basic.FormTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fform_005f0);
    try {
      _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
      // /ShowPatientMedicalHistory.jsp(18,8) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fform_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(18,8) 'space-y-6'",_jsp_getExpressionFactory().createValueExpression("space-y-6",java.lang.String.class)));
      _jspx_th_h_005fform_005f0.setJspId("jsp_1705704282_1");
      int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fform_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("            <!-- Input Row -->\r\n");
          out.write("            <div class=\"flex flex-wrap items-center gap-4\">\r\n");
          out.write("                ");
          if (_jspx_meth_h_005foutputLabel_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005finputText_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcommandButton_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcommandButton_005f1(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("\r\n");
          out.write("            <!-- Data Table -->\r\n");
          out.write("            ");
          if (_jspx_meth_h_005fdataTable_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fform_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputLabel_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLabel
    com.sun.faces.taglib.html_basic.OutputLabelTag _jspx_th_h_005foutputLabel_005f0 = new com.sun.faces.taglib.html_basic.OutputLabelTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputLabel_005f0);
    try {
      _jspx_th_h_005foutputLabel_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputLabel_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /ShowPatientMedicalHistory.jsp(22,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(22,16) 'Enter Patient ID:'",_jsp_getExpressionFactory().createValueExpression("Enter Patient ID:",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(22,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(22,16) 'text-gray-700 font-medium'",_jsp_getExpressionFactory().createValueExpression("text-gray-700 font-medium",java.lang.String.class)));
      _jspx_th_h_005foutputLabel_005f0.setJspId("jsp_1705704282_2");
      int _jspx_eval_h_005foutputLabel_005f0 = _jspx_th_h_005foutputLabel_005f0.doStartTag();
      if (_jspx_th_h_005foutputLabel_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputLabel_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    com.sun.faces.taglib.html_basic.InputTextTag _jspx_th_h_005finputText_005f0 = new com.sun.faces.taglib.html_basic.InputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005finputText_005f0);
    try {
      _jspx_th_h_005finputText_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005finputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /ShowPatientMedicalHistory.jsp(23,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(23,16) '#{medicationHistoryController.patient.patientId}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{medicationHistoryController.patient.patientId}",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(23,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(23,16) 'border border-gray-300 px-3 py-2 rounded'",_jsp_getExpressionFactory().createValueExpression("border border-gray-300 px-3 py-2 rounded",java.lang.String.class)));
      _jspx_th_h_005finputText_005f0.setJspId("jsp_1705704282_3");
      int _jspx_eval_h_005finputText_005f0 = _jspx_th_h_005finputText_005f0.doStartTag();
      if (_jspx_th_h_005finputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005finputText_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcommandButton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandButton
    com.sun.faces.taglib.html_basic.CommandButtonTag _jspx_th_h_005fcommandButton_005f0 = new com.sun.faces.taglib.html_basic.CommandButtonTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcommandButton_005f0);
    try {
      _jspx_th_h_005fcommandButton_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcommandButton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /ShowPatientMedicalHistory.jsp(25,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(25,16) 'Search'",_jsp_getExpressionFactory().createValueExpression("Search",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(25,16) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object action()
      _jspx_th_h_005fcommandButton_005f0.setAction(new org.apache.jasper.el.JspMethodExpression("/ShowPatientMedicalHistory.jsp(25,16) '#{medicationHistoryController.loadPatientMedicalHistory}'",_jsp_getExpressionFactory().createMethodExpression(_jspx_page_context.getELContext(),"#{medicationHistoryController.loadPatientMedicalHistory}",java.lang.Object.class,new java.lang.Class[] {})));
      // /ShowPatientMedicalHistory.jsp(25,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(25,16) 'bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700'",_jsp_getExpressionFactory().createValueExpression("bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700",java.lang.String.class)));
      _jspx_th_h_005fcommandButton_005f0.setJspId("jsp_1705704282_4");
      int _jspx_eval_h_005fcommandButton_005f0 = _jspx_th_h_005fcommandButton_005f0.doStartTag();
      if (_jspx_th_h_005fcommandButton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcommandButton_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcommandButton_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandButton
    com.sun.faces.taglib.html_basic.CommandButtonTag _jspx_th_h_005fcommandButton_005f1 = new com.sun.faces.taglib.html_basic.CommandButtonTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcommandButton_005f1);
    try {
      _jspx_th_h_005fcommandButton_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcommandButton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /ShowPatientMedicalHistory.jsp(27,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(27,16) '📋 Menu'",_jsp_getExpressionFactory().createValueExpression("📋 Menu",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(27,16) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object action()
      _jspx_th_h_005fcommandButton_005f1.setAction(new org.apache.jasper.el.JspMethodExpression("/ShowPatientMedicalHistory.jsp(27,16) '#{doctorController.goToMedicationDashboard}'",_jsp_getExpressionFactory().createMethodExpression(_jspx_page_context.getELContext(),"#{doctorController.goToMedicationDashboard}",java.lang.Object.class,new java.lang.Class[] {})));
      // /ShowPatientMedicalHistory.jsp(27,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f1.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(27,16) 'bg-gray-600 text-white px-4 py-2 rounded hover:bg-gray-700'",_jsp_getExpressionFactory().createValueExpression("bg-gray-600 text-white px-4 py-2 rounded hover:bg-gray-700",java.lang.String.class)));
      _jspx_th_h_005fcommandButton_005f1.setJspId("jsp_1705704282_5");
      int _jspx_eval_h_005fcommandButton_005f1 = _jspx_th_h_005fcommandButton_005f1.doStartTag();
      if (_jspx_th_h_005fcommandButton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcommandButton_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fdataTable_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:dataTable
    com.sun.faces.taglib.html_basic.DataTableTag _jspx_th_h_005fdataTable_005f0 = new com.sun.faces.taglib.html_basic.DataTableTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fdataTable_005f0);
    try {
      _jspx_th_h_005fdataTable_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fdataTable_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /ShowPatientMedicalHistory.jsp(32,12) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(32,12) '#{medicationHistoryController.medicalHistoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{medicationHistoryController.medicalHistoryList}",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(32,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setVar("med");
      // /ShowPatientMedicalHistory.jsp(32,12) name = rendered type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = boolean deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setRendered(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(32,12) '#{not empty medicationHistoryController.medicalHistoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{not empty medicationHistoryController.medicalHistoryList}",boolean.class)));
      // /ShowPatientMedicalHistory.jsp(32,12) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(32,12) 'min-w-full border border-gray-300 mt-8 rounded overflow-hidden'",_jsp_getExpressionFactory().createValueExpression("min-w-full border border-gray-300 mt-8 rounded overflow-hidden",java.lang.String.class)));
      _jspx_th_h_005fdataTable_005f0.setJspId("jsp_1705704282_6");
      int _jspx_eval_h_005fdataTable_005f0 = _jspx_th_h_005fdataTable_005f0.doStartTag();
      if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fdataTable_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f0(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f1(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f2(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f3(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_h_005fdataTable_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fdataTable_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fdataTable_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f0 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f0);
    try {
      _jspx_th_h_005fcolumn_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f0.setJspId("jsp_1705704282_7");
      int _jspx_eval_h_005fcolumn_005f0 = _jspx_th_h_005fcolumn_005f0.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f0(_jspx_th_h_005fcolumn_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f1(_jspx_th_h_005fcolumn_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f0 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f0_reused = false;
    try {
      _jspx_th_f_005ffacet_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f0);
      // /ShowPatientMedicalHistory.jsp(37,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f0.setName("header");
      int _jspx_eval_f_005ffacet_005f0 = _jspx_th_f_005ffacet_005f0.doStartTag();
      if (_jspx_eval_f_005ffacet_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_h_005foutputText_005f0(_jspx_th_f_005ffacet_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f0);
      _jspx_th_f_005ffacet_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f0, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f0 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f0);
    try {
      _jspx_th_h_005foutputText_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f0);
      // /ShowPatientMedicalHistory.jsp(38,24) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(38,24) 'Med ID'",_jsp_getExpressionFactory().createValueExpression("Med ID",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(38,24) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(38,24) 'font-semibold bg-gray-100 p-2 block'",_jsp_getExpressionFactory().createValueExpression("font-semibold bg-gray-100 p-2 block",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f0.setJspId("jsp_1705704282_8");
      int _jspx_eval_h_005foutputText_005f0 = _jspx_th_h_005foutputText_005f0.doStartTag();
      if (_jspx_th_h_005foutputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f1 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f1);
    try {
      _jspx_th_h_005foutputText_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f0);
      // /ShowPatientMedicalHistory.jsp(40,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(40,20) '#{med.medId}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{med.medId}",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(40,20) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f1.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(40,20) 'p-2 block'",_jsp_getExpressionFactory().createValueExpression("p-2 block",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f1.setJspId("jsp_1705704282_9");
      int _jspx_eval_h_005foutputText_005f1 = _jspx_th_h_005foutputText_005f1.doStartTag();
      if (_jspx_th_h_005foutputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f1 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f1);
    try {
      _jspx_th_h_005fcolumn_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f1.setJspId("jsp_1705704282_10");
      int _jspx_eval_h_005fcolumn_005f1 = _jspx_th_h_005fcolumn_005f1.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f1);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f1(_jspx_th_h_005fcolumn_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f3(_jspx_th_h_005fcolumn_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f1 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f1_reused = false;
    try {
      _jspx_th_f_005ffacet_005f1.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f1);
      // /ShowPatientMedicalHistory.jsp(44,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f1.setName("header");
      int _jspx_eval_f_005ffacet_005f1 = _jspx_th_f_005ffacet_005f1.doStartTag();
      if (_jspx_eval_f_005ffacet_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_h_005foutputText_005f2(_jspx_th_f_005ffacet_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f1);
      _jspx_th_f_005ffacet_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f1, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f2 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f2);
    try {
      _jspx_th_h_005foutputText_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f1);
      // /ShowPatientMedicalHistory.jsp(45,24) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(45,24) 'Patient ID'",_jsp_getExpressionFactory().createValueExpression("Patient ID",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(45,24) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f2.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(45,24) 'font-semibold bg-gray-100 p-2 block'",_jsp_getExpressionFactory().createValueExpression("font-semibold bg-gray-100 p-2 block",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f2.setJspId("jsp_1705704282_11");
      int _jspx_eval_h_005foutputText_005f2 = _jspx_th_h_005foutputText_005f2.doStartTag();
      if (_jspx_th_h_005foutputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f3 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f3);
    try {
      _jspx_th_h_005foutputText_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f1);
      // /ShowPatientMedicalHistory.jsp(47,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(47,20) '#{med.patient.patientId}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{med.patient.patientId}",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(47,20) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f3.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(47,20) 'p-2 block'",_jsp_getExpressionFactory().createValueExpression("p-2 block",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f3.setJspId("jsp_1705704282_12");
      int _jspx_eval_h_005foutputText_005f3 = _jspx_th_h_005foutputText_005f3.doStartTag();
      if (_jspx_th_h_005foutputText_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f2 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f2);
    try {
      _jspx_th_h_005fcolumn_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f2.setJspId("jsp_1705704282_13");
      int _jspx_eval_h_005fcolumn_005f2 = _jspx_th_h_005fcolumn_005f2.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f2);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f2(_jspx_th_h_005fcolumn_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f5(_jspx_th_h_005fcolumn_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f2 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f2_reused = false;
    try {
      _jspx_th_f_005ffacet_005f2.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f2);
      // /ShowPatientMedicalHistory.jsp(51,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f2.setName("header");
      int _jspx_eval_f_005ffacet_005f2 = _jspx_th_f_005ffacet_005f2.doStartTag();
      if (_jspx_eval_f_005ffacet_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_h_005foutputText_005f4(_jspx_th_f_005ffacet_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f2);
      _jspx_th_f_005ffacet_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f2, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f4 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f4);
    try {
      _jspx_th_h_005foutputText_005f4.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f2);
      // /ShowPatientMedicalHistory.jsp(52,24) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(52,24) 'Medicines'",_jsp_getExpressionFactory().createValueExpression("Medicines",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(52,24) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f4.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(52,24) 'font-semibold bg-gray-100 p-2 block'",_jsp_getExpressionFactory().createValueExpression("font-semibold bg-gray-100 p-2 block",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f4.setJspId("jsp_1705704282_14");
      int _jspx_eval_h_005foutputText_005f4 = _jspx_th_h_005foutputText_005f4.doStartTag();
      if (_jspx_th_h_005foutputText_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f5 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f5);
    try {
      _jspx_th_h_005foutputText_005f5.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f2);
      // /ShowPatientMedicalHistory.jsp(54,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(54,20) '#{med.medicines}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{med.medicines}",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(54,20) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f5.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(54,20) 'p-2 block'",_jsp_getExpressionFactory().createValueExpression("p-2 block",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f5.setJspId("jsp_1705704282_15");
      int _jspx_eval_h_005foutputText_005f5 = _jspx_th_h_005foutputText_005f5.doStartTag();
      if (_jspx_th_h_005foutputText_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f5, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f3 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f3);
    try {
      _jspx_th_h_005fcolumn_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f3.setJspId("jsp_1705704282_16");
      int _jspx_eval_h_005fcolumn_005f3 = _jspx_th_h_005fcolumn_005f3.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f3);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f3(_jspx_th_h_005fcolumn_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f7(_jspx_th_h_005fcolumn_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f3 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f3_reused = false;
    try {
      _jspx_th_f_005ffacet_005f3.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f3);
      // /ShowPatientMedicalHistory.jsp(58,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f3.setName("header");
      int _jspx_eval_f_005ffacet_005f3 = _jspx_th_f_005ffacet_005f3.doStartTag();
      if (_jspx_eval_f_005ffacet_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_h_005foutputText_005f6(_jspx_th_f_005ffacet_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f3);
      _jspx_th_f_005ffacet_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f3, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f6 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f6);
    try {
      _jspx_th_h_005foutputText_005f6.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f3);
      // /ShowPatientMedicalHistory.jsp(59,24) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f6.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(59,24) 'Tests'",_jsp_getExpressionFactory().createValueExpression("Tests",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(59,24) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f6.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(59,24) 'font-semibold bg-gray-100 p-2 block'",_jsp_getExpressionFactory().createValueExpression("font-semibold bg-gray-100 p-2 block",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f6.setJspId("jsp_1705704282_17");
      int _jspx_eval_h_005foutputText_005f6 = _jspx_th_h_005foutputText_005f6.doStartTag();
      if (_jspx_th_h_005foutputText_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f6, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f7 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f7);
    try {
      _jspx_th_h_005foutputText_005f7.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f3);
      // /ShowPatientMedicalHistory.jsp(61,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f7.setValue(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(61,20) '#{med.tests}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{med.tests}",java.lang.Object.class)));
      // /ShowPatientMedicalHistory.jsp(61,20) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f7.setStyleClass(new org.apache.jasper.el.JspValueExpression("/ShowPatientMedicalHistory.jsp(61,20) 'p-2 block'",_jsp_getExpressionFactory().createValueExpression("p-2 block",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f7.setJspId("jsp_1705704282_18");
      int _jspx_eval_h_005foutputText_005f7 = _jspx_th_h_005foutputText_005f7.doStartTag();
      if (_jspx_th_h_005foutputText_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f7, _jsp_getInstanceManager(), false);
    }
    return false;
  }
}
